version: '3'

services:

  todoback:
    image: todobackend
    restart: always
    ports: 
      - 3031:3031

  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST: todoback

  todotests:
    image: todotests
    restart: always
    environment:
      - FRONT_HOST: todofront
    depends_on:
      - todofront
      - todoback